version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@babel/register"
    versions:
    - 7.12.10
    - 7.13.8
  - dependency-name: "@babel/core"
    versions:
    - 7.12.17
    - 7.12.9
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.0
    - 3.3.1
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.10
  - dependency-name: babel-plugin-react-intl
    versions:
    - 8.2.21
  - dependency-name: webpack-dev-middleware
    versions:
    - 4.0.2
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
